---
title: "Settings"
output: html_notebook
---

```{r}
cave::rmAll()
source('~/GitHub/omop_mapping/01 procedure/config/funs.R')
```


```{r projectsettings}
# Project Setup
project_name <- "CBIOPORTAL"
origin_fn <-  "~/Memorial Sloan Kettering Cancer Center/cBioPortal Standardization - KMI Only - KMI Only/Mapping Files/cBioPortal_Workfile.xlsx"
origin_tab <- "MAP_20"

```

```{r requiredinputs}
# Target Columns: column where queries are sourced from. Note that the column called "CONCEPT" has been changed to "SOURCE" in this routine since the merge of OMOP concepts is functionalized to be called `Concept`.
## Source Columns: 1:1 concepts
#input_file_stem <- "ESOPHAGUS_"
source_col <- "CONCEPT"
word_split <- "[ ]{1}|[(]{1}|[)]{1}|[,]{1}|[/]{1}|[+]{1}|[-]{1}[>]{1}" #The regex to split() the SOURCE column on to retrieve words for words-based searches


# Terminal Column: name of the column in the input that, if populated, indicates that a concept has been mapped and further search routines are ignored
terminal_col <- "Fact"

# Skip parameters: parameters that signals skipping over a concept
source_skip_nchar <- 3
additional_filters <- list('!is.na(ONCOTREE_NAME)')

```

```{r optionalinputs}
word_split <- "[ ]{1}|[(]{1}|[)]{1}|[,]{1}|[/]{1}|[+]{1}|[-]{1}[>]{1}" #The regex to split() the SOURCE column on to retrieve words for words-based searches

## Term Columns: series of search terms and phrases to each original concept to further search for the concept. Term columns are manually inputed by an end-user.
search_term_col <- NULL
attribute_col <- NULL
regimen_col <- NULL
component_col <- NULL


additional_filters <- list('!is.na(ONCOTREE_NAME)')

```


```{r outputsettings}

# Search Settings
# Global filters for all queries to the concept table
vocabulary_id <- c("SNOMED")
concept_class_id <- NULL
domain_id <- "Observation"
standard_concept <- NULL
invalid_reason <- NA

```


```{r executesetup, eval=TRUE}

setupProjectDirs()
saveSettings()
createSettingsObj()

```

```{r}

```

