output_colnames <-
c("routine_id",
  "Source Exact",
  "Source Like",
  "Source String as Vector",
  "Search Term Exact",
  "Search Term Like",
  "Search Term Synonym Exact",
  "Search Term Synonym Like",
  "Search Term Synonym Str As Vector",
  "Search Term String as Vector",
  "Source Synonym Like",
  "Source Synonym Exact",
  "Source First Word Exact",
  "Source First Word Like",
  "Source No Parentheses Exact",
  "Source No Parentheses Like",
  "Source No Parentheses Str as Vector",
  "Source Remove ICDO3 Code Like",
  "Source Remove ICDO3 Code Exact",
  "Source ICDO3 Code",
  "Source Remove ICDO3 Str as Vector",
  "Source Remove ICDO3 Synonym Exact",
  "Source Remove ICDO3 Synonym Like",
  "Source Numbers Exact",
  "Source Numbers Like",
  "Source Each Word Exact",
  "Source Numbers as Words Exact",
  "Source Numbers as Words Like",
  "Source After Colon Exact",
  "Source After Colon Like",
  "Source Longest Word Exact",
  "Source Longest Word Like")